repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -    id: isort
         entry: isort --check
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        entry: black --check
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.0'  
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
        additional_dependencies: [sqlalchemy2-stubs <= 0.0.2a20, SQLAlchemy <= 1.4]
