repos:
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -    id: isort
         entry: poetry run isort
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        entry: poetry run black
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        entry: poetry run flake8 buildingmotif
# can't poetry run becuase not present in repository https://github.com/pre-commit/mirrors-mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
    -   id: mypy
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports", "--follow-imports=skip", "--disable-error-code=import-untyped"]
        additional_dependencies: [sqlalchemy2-stubs <= 0.0.2a38, SQLAlchemy < 1.5]
exclude: docs/conf.py
