repos:
-   repo: https://github.com/gvanderest/pylama-pre-commit
    rev: 0.1.2
    hooks:
    -   id: pylama
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        entry: black --check
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -    id: isort
         entry: isort --check
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
