version: "1.0"
services:
  db:
    container_name: buildingmotif-db
    image: postgres
    environment:
      - POSTGRES_DB=buildingmotif
      - POSTGRES_USER=buildingmotif
      - POSTGRES_PASSWORD=password
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host

  api:
    container_name: buildingmotif-api
    build: .
    image: buildingmotif-api:latest
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    entrypoint: poetry run python /buildingmotif/buildingmotif/api/app.py

  app:
    container_name: buildingmotif-app
    build: ./buildingmotif-app
    image: buildingmotif-app:latest
    ports:
      - target: 4200
        published: 4200
        protocol: tcp
        mode: host
