"""Create ValidationContext

Revision ID: 040e0be1f771
Revises: 6114d2b80bc6
Create Date: 2023-11-16 01:01:25.292086

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "040e0be1f771"
down_revision = "6114d2b80bc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validation_context",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("report_string", sa.TEXT(), nullable=False),
        sa.Column("report_id", sa.String(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "validation_context_shape_collection_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shape_collection_id", sa.Integer(), nullable=True),
        sa.Column("validation_context_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shape_collection_id"],
            ["shape_collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["validation_context_id"],
            ["validation_context.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "shape_collection_id",
            "validation_context_id",
            name="validation_context_shape_collection_unique_constraint",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("validation_context_shape_collection_association")
    op.drop_table("validation_context")
    # ### end Alembic commands ###
