"""Add ShapeCollections

Revision ID: 3fcdf6f2886b
Revises: ee47e252795d
Create Date: 2022-06-20 15:51:36.992384

"""
import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import sessionmaker

from buildingmotif.database.tables import DBShapeCollection, DBTemplateLibrary

# revision identifiers, used by Alembic.
revision = "3fcdf6f2886b"
down_revision = "ee47e252795d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shape_collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("graph_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("template_library", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("shape_collection_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "tempalte_library_shape_collection",
            "shape_collection",
            ["shape_collection_id"],
            ["id"],
        )

    conn = op.get_bind()
    Session = sessionmaker()

    with Session(bind=conn) as session:
        template_libraries = session.query(DBTemplateLibrary).all()

        for tl in template_libraries:
            shape_collection = DBShapeCollection(graph_id=str(uuid.uuid4()))
            session.add(shape_collection)
            tl.shape_collection = shape_collection

        session.commit()

    with op.batch_alter_table("template_library", schema=None) as batch_op:
        batch_op.alter_column("shape_collection_id", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("template_library", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("shape_collection_id")

    op.drop_table("shape_collection")
    # ### end Alembic commands ###
