"""Constrain dependencies to have no duplicates. Uses new JSON serde

Revision ID: 542bfbdef624
Revises: 66121a0432bc
Create Date: 2022-09-13 10:57:44.977492

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import sessionmaker

from buildingmotif.database.tables import DepsAssociation
from buildingmotif.database.utils import _custom_json_serializer

# revision identifiers, used by Alembic.
revision = "542bfbdef624"
down_revision = "66121a0432bc"
branch_labels = None
depends_on = None


def upgrade():
    # update the serde of the deps field by copying all the deps
    # out and then putting them back in
    conn = op.get_bind()
    Session = sessionmaker()
    Session.json_serializer = _custom_json_serializer

    with Session(bind=conn) as session:
        deps = session.query(DepsAssociation).all()

        for dep in deps:
            dep.args = dep.args.copy()

        session.commit()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deps_association_table", schema=None) as batch_op:

        batch_op.add_column(sa.Column("id", sa.Integer(), nullable=False))
        batch_op.alter_column("dependant_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("dependee_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_unique_constraint(
            "deps_association_unique_constraint",
            ["dependant_id", "dependee_id", "args"],
        )

    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.drop_index("ix_template_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.create_index("ix_template_name", ["name"], unique=False)

    with op.batch_alter_table("deps_association_table", schema=None) as batch_op:
        batch_op.drop_constraint("deps_association_unique_constraint", type_="unique")
        batch_op.alter_column("dependee_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "dependant_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_column("id")

    # ### end Alembic commands ###
