"""init

Revision ID: 6114d2b80bc6
Revises: 
Create Date: 2023-10-16 20:10:01.622863

"""
import sqlalchemy as sa
from alembic import op

# from sqlalchemy.dialects.postgresql import JSON
from buildingmotif.database.utils import JSONType

# revision identifiers, used by Alembic.
revision = "6114d2b80bc6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shape_collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("graph_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "library",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("shape_collection_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shape_collection_id"],
            ["shape_collection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("graph_id", sa.String(), nullable=True),
        sa.Column("manifest_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["shape_collection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("body_id", sa.String(), nullable=True),
        sa.Column("optional_args", JSONType(), nullable=True),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["library.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "library_id", name="name_library_unique_constraint"
        ),
    )
    op.create_table(
        "deps_association_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dependant_id", sa.Integer(), nullable=True),
        sa.Column("dependee_id", sa.Integer(), nullable=True),
        sa.Column("args", JSONType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dependant_id"],
            ["template.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dependee_id"],
            ["template.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dependant_id",
            "dependee_id",
            "args",
            name="deps_association_unique_constraint",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deps_association_table")
    op.drop_table("template")
    op.drop_table("models")
    op.drop_table("library")
    op.drop_table("shape_collection")
    # ### end Alembic commands ###
