"""add optional_args to template

Revision ID: 66121a0432bc
Revises: 3fcdf6f2886b
Create Date: 2022-07-02 17:02:43.455056

"""
import sqlalchemy as sa
from alembic import op

from buildingmotif.database.utils import JSONType

# revision identifiers, used by Alembic.
revision = "66121a0432bc"
down_revision = "3fcdf6f2886b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.add_column(sa.Column("optional_args", JSONType(), nullable=True))
        batch_op.create_index(batch_op.f("ix_template_name"), ["name"], unique=False)
        batch_op.drop_column("_head")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.add_column(sa.Column("_head", sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_template_name"))
        batch_op.drop_column("optional_args")

    # ### end Alembic commands ###
