"""Add description to Model

Revision ID: 99fd5e88689c
Revises: 66121a0432bc
Create Date: 2022-09-26 11:37:39.308986

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "99fd5e88689c"
down_revision = "66121a0432bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.Text(), nullable=False, server_default="")
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
