"""Constrain dependencies to have no duplicates. Uses new JSON serde

Revision ID: c69f87d3994b
Revises: 66121a0432bc
Create Date: 2022-09-13 10:56:37.472803

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c69f87d3994b"
down_revision = "66121a0432bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deps_association_table", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.Integer(), nullable=False))
        batch_op.alter_column("dependant_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("dependee_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.drop_index("ix_template_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.create_index("ix_template_name", ["name"], unique=False)

    with op.batch_alter_table("deps_association_table", schema=None) as batch_op:
        batch_op.alter_column("dependee_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "dependant_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_column("id")

    # ### end Alembic commands ###
