# https://jupyterbook.org/en/stable/customize/config.html

# Book settings
title                       : BuildingMOTIF Documentation
author                      : NREL
copyright                   : "2023"
logo                        : BuildingMOTIF-logo-rev.svg

# Execution settings
# Force re-execution of notebooks on each build. https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks         : force
  timeout                   : 300
  allow_errors              : true

# Parse and render settings

# HTML-specific settings
html:
  favicon                   : BuildingMOTIF-icon-rev.svg
  announcement              : "⚠️ This is an BETA release for testing purposes only ⚠️"
  use_repository_button     : true

# LaTeX-specific settings
latex:
  latex_documents:
    targetname              : BuildingMOTIF.tex
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - bibliography.bib


# Launch button settings
repository:
  url                       : https://github.com/NREL/BuildingMOTIF
  path_to_book              : docs  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

# Advanced and power-user settings
# for API autodocs added to jupyter book
sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.viewcode'
  config:
    autosummary_generate    : true
    add_module_names        : false

    # Autodoc config reference
    # https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#configuration
    autodoc_default_options:
      members               : true
      member-order          : bysource
      undoc-members         : true
      private-members       : false
