name: continuous integration

on:
  push

jobs:

  style:
    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/workflows/setup.yml@ci-cleanup
    # - uses: actions/checkout@v3
    # - uses: actions/setup-python@v4
    # - uses: snok/install-poetry@v1
    #   with:
    #     virtualenvs-in-project: false
    #     virtualenvs-path: ~/.virtualenvs
    # - run: poetry install

    - name: Style
      run: |
        poetry run pylama
        poetry run black . --check
        poetry run isort . --check
        poetry run mypy buildingmotif/*.py tests/*.py migrations/*.py

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry 
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install dependencies
      run: poetry install

    - name: Run unit tests with pytest
      run: poetry run pytest  tests/unit --cov=./ --cov-report=xml

    - name: Run integration tests with pytest
      run: poetry run pytest tests/integration

    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
