name: continuous integration

on:
  push

jobs:

  style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup-python
        uses: actions/setup-python@main
      - name: install-poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs
      - run: |
          poetry install
          poetry run pylama
          poetry run black . --check
          poetry run isort . --check

  tests:
    needs: style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup-python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs
      - name: poetry install
        run: poetry install
      - name: static type checks
        run: poetry run mypy buildingmotif/*.py tests/*.py migrations/*.py
      - name: unit tests
        run: poetry run pytest tests/unit --cov=./ --cov-report=xml
      - name: integration tests
        run: poetry run pytest tests/integration
      - name: build tests
        run: poetry build

  coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: codecov/codecov-action@main
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
