name: continuous integration

on:
  push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  styling:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install-poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs
      - name: poetry install
        run: poetry install --all-extras
      - name: run isort and black
        run: |
          poetry run isort . --check
          poetry run black . --check

  testing:
    needs: styling
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4 # for topquadrant shacl support
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs
      - name: poetry install
        run: poetry install --all-extras
      - name: lint
        run: poetry run flake8 buildingmotif
      - name: type check
        run: poetry run mypy --ignore-missing-imports
      - name: unit tests
        run: poetry run pytest tests/unit --cov=./ --cov-report=xml
      - name: integration tests
        run: poetry run pytest tests/integration
      - name: library tests
        run: poetry run pytest tests/library
      - name: bacnet tests
        run: |
          cd tests/integration/fixtures/bacnet
          docker compose build device buildingmotif
          docker compose run -d device
          docker compose run buildingmotif poetry run pytest -m bacnet --skip-library-tests
          docker compose down
      - name: build tests
        run: poetry build

  coverage:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
