name: build-docs

on:
  push:
    branches:
    - reenable-docs
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4

    - name: install dependencies
      run: |
        pip install poetry
        poetry install

    - name: install project
      run: pip install -e .

    - name: install jupyter book
      run: pip install -U jupyter-book

    - name: build jupyter book
      working-directory: ${{runner.workspace}}/BuildingMOTIF/docs/
      run: |
        jupyter-book build .

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
