name: Auto Assign Issues and PRs to Projects

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
      - name: Assign New issues and New pull requests to project FY23
        uses: srggrs/assign-one-project-github-action@1.3.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/NREL/BuildingMOTIF/projects/2'
