name: Tests and Style

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install Poetry 
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install dependencies
      run: poetry install

    - name: Run unit tests with pytest
      run: poetry run pytest --cov=./ --cov-report=xml

    - name: Run integration tests with pytest
      run: poetry run pytest -m integration

    - name: Codecov
      uses: codecov/codecov-action@v2.1.0

  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install Poetry 
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install dependencies
      run: poetry install

    - name: Style
      run: |
        poetry run pylama
        poetry run black . --check
        poetry run isort . --check
        poetry run mypy buildingmotif/*.py tests/*.py
