name: Tests and Style

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install Poetry 
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install dependencies
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest tests

  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install Poetry 
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install dependencies
      run: poetry install

    - name: Style
      run: |
        poetry run pylama
        poetry run black . --check
        poetry run isort . --check