# https://github.com/githubocto/repo-visualizer

name: repo-vis

on:
  workflow_dispatch: {}
  push:
    branches:
      - add/repo-vis

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          output_file: "repo-vis.svg"
          artifact_name: "repo-vis"
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: "repo-vis"
          path: "downloads"
