# https://github.com/githubocto/repo-visualizer

name: repo-vis

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  repo-vis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@main

      - name: update repo diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: docs/reference/apidoc/diagram.svg
          excluded_paths: ".github"
          commit_message: "update repo diagram [skip ci]"
